### ISSUE TITLE
Last known Todo App Problem

### ISSUE THREAD

**Issue by i1Zeus** [EnabApp/Utilities#7]

**Comment by i1Zeus** [comment]
![Image](https://user-images.githubusercontent.com/98782046/187077837-16b4325c-cad0-4154-8983-aa6df0249833.png)

**Comment by Gruce** [comment]
Hello @i1Zeus 
Have you checked this solution? 
https://stackoverflow.com/questions/28234572/html5-datetime-local-chrome-how-to-input-datetime-in-current-time-zone

**Comment by i1Zeus** [comment]
Hi, @Gruce 
The reason that this warning is showing because when the data is fetched from the database it's coming as **timestampz** , the warning is completely fix when updating or adding tasks
